/**
 * `cron` domain (L5) — `IAgentCronService` contract.
 *
 * Owns the agent's set of scheduled cron tasks and the queries the cron tools
 * and the edge layer need against them. The data record (`CronTask`) lives here
 * beside the contract because every method takes or returns it. Bound at Agent
 * scope.
 */

import type { ContentPart } from '@moonshot-ai/kosong';

import { createDecorator } from '#/_base/di';
import type { Turn } from '#/agent/turn';

/**
 * Persistent representation of a cron task.
 *
 *   - `id` — 8-hex; jitter is keyed off this hash, so a stable id == stable
 *     jitter across schedule rewrites.
 *   - `cron` — 5-field expression, evaluated in local time.
 *   - `createdAt` — wall-clock epoch ms at original scheduling. NOT updated
 *     when the scheduler fires; recurring uses it as the baseline floor when
 *     no `lastFiredAt` has been recorded. Also the input to the 7-day stale
 *     judgment.
 *   - `recurring` — undefined / true means "fire repeatedly until deleted or
 *     auto-expired"; false means "fire once then auto-delete".
 *   - `lastFiredAt` — wall-clock epoch ms of the last ideal occurrence whose
 *     jittered delivery has actually completed. Persisted so a `kimi resume`
 *     does not replay already-delivered recurring fires. A value greater than
 *     the current wall clock is treated as corrupt and ignored.
 */
export interface CronTask {
  readonly id: string;
  readonly cron: string;
  readonly prompt: string;
  readonly createdAt: number;
  readonly recurring?: boolean;
  readonly lastFiredAt?: number;
}

/** Everything the caller supplies; `id` and `createdAt` are generated by the service. */
export type CronTaskInit = Omit<CronTask, 'id' | 'createdAt'>;

export interface CronOptions {
  readonly isSubagent?: boolean;
}

export interface CronLoadOptions {
  readonly replace?: boolean;
}

export interface IAgentCronService {
  readonly _serviceBrand: undefined;
  readonly isEnabled: boolean;

  // —— task CRUD (used by the cron tools and the edge layer) ——
  addTask(init: CronTaskInit): CronTask;
  removeTasks(ids: readonly string[]): readonly string[];
  getTask(id: string): CronTask | undefined;
  list(): readonly CronTask[];

  // —— scheduling queries (used by the cron tools and monitoring) ——
  /** Wall-clock epoch ms read through the configured clock source. */
  now(): number;
  isStale(task: CronTask): boolean;
  getNextFireTime(): number | null;
  getNextFireForTask(taskId: string): number | null;

  // —— lifecycle (driven by the engine, resume, and the test seam) ——
  loadFromDisk(options?: CronLoadOptions): Promise<void>;
  start(): void;
  stop(): Promise<void>;
  tick(): void;
  flushPersist(): Promise<void>;
  handleMissed(
    tasks: readonly CronTask[],
    renderMissedNotification: (tasks: readonly CronTask[]) => readonly ContentPart[],
  ): Turn | undefined;

  // —— telemetry facade so the tools do not reach into ITelemetryService ——
  emitScheduled(task: CronTask): void;
  emitDeleted(taskId: string): void;
}

export const IAgentCronService = createDecorator<IAgentCronService>('agentCronService');
